### ISSUE TITLE
Console error running dashboard-app example

### ISSUE THREAD

**Issue by iotaweb** [stormpath/stormpath-sdk-angularjs#7] opened 2015-04-11 00:14 UTC
Hello,

I followed the instructions to run the **dashboard-app** example, but unfortunately, I get the following error in the console when viewing the Register page:

```
TypeError: undefined is not a function
    at Object.definition.$get (<anonymous>:324:30)
    at Object.invoke (angular.js:4203)
    at angular.js:4021
    at getService (angular.js:4162)
    at Object.invoke (angular.js:4194)
    at extend.instance (angular.js:8493)
    at angular.js:7739
    at forEach (angular.js:331)
    at nodeLinkFn (angular.js:7738)
    at angular.js:7998angular.js:11655 (anonymous function)
```

The page loads, but it is clearly broken and will not register a  user.

Any ideas or help to get this app running would be appreciated!

Regards, Rob

**Comment by robertjd** [comment] 2015-04-11 00:51
Hi @iotaweb ,

That's a strange one, unfortunately I was unable to reproduce it.  A few questions:
- Do you get any errors while running `grunt serve`?  
- Did Bower ask you to manually resolve any dependencies?

While running the example just now, I realized that the instructions on the Readme were a bit misleading on the Stormpath configuration, so I just updated that section - can you check it out too?

Thanks!

**Comment by iotaweb** [comment] 2015-04-11 01:51
Hi @robertjd,

I didn't see any errors while running `grunt serve`, output below:

```
okapi:dashboard-app rob$ grunt serve
Running "serve" task

Running "clean:server" (clean) task

Running "env:all" (env) task

Running "concurrent:server" (concurrent) task

Running "injector:scripts" (injector) task
Missing option `template`, using `dest` as template instead
Injecting js files (15 files)
>> Nothing changed

Running "injector:css" (injector) task
Missing option `template`, using `dest` as template instead
Injecting css files (8 files)
>> Nothing changed

Running "wiredep:target" (wiredep) task

Running "autoprefixer:dist" (autoprefixer) task

Running "express:dev" (express) task
Starting background Express server
debugger listening on port 5858
Initializing Stormpath Client

Running "wait" task
>> Waiting for server reload...
Initializing Stormpath Application
Express server listening on 9000, in development mode
Done waiting!

Running "open:server" (open) task

Running "watch" task
Waiting...
GET /api/users/current 401 5ms - 42b
GET /api/things 401 2ms - 42b
GET /api/things 401 1ms - 42b
Sat, 11 Apr 2015 01:21:30 GMT express deprecated res.sendfile: Use res.sendFile instead at server/routes.js:26:11
GET /register 200 48ms
GET /api/users/current 401 1ms - 42b
```

Thanks for updating the instructions - I had added my Stormpath config values as described, so I don't think this was the problem. There were also no dependency issues reported with bower.

One thing I did try was try Safari (previously I was using Chrome  - Mac OS X 10.9). When using Safari, I could register successfully, but could not login. I don't think the token verification worked (I was careful to change the URL of the verification link to use port 9000 to match my express server).

When I try to login, I get the following error (and the user in Stormpath admin remains unverified):

```
{"errorMessage":"Invalid username or password."}
```

So it looks like there is definitely something fishy with Chrome and I can only get part way with Safari... :/

**Comment by robertjd** [comment] 2015-04-13 21:50
That is fishy.. can you tell me which version of Chrome you are using?

**Comment by iotaweb** [comment] 2015-04-13 22:06
Chrome Version 41.0.2272.118 (64-bit) 
Mac OS X 10.9 Mavericks  - Mac Book Pro

**Comment by robertjd** [comment] 2015-04-13 22:42
Could you share you code with us?  I'm pretty puzzled by this one.  If not here you can hit us on support@stormpath.com as well

**Comment by robertjd** [comment] 2015-06-16 17:56
Following up on this one as it's a few months old now, any luck @iotaweb ?

**Comment by iotaweb** [comment] 2015-06-22 00:29
@robertjd - sorry for the delay in responding, I've been working on another project. 

I downloaded the latest and this time I can register successfully using Chrome. However the email-verification link is not correctly setting the verification flag to 'Enabled', so I cannot login. If I manually set it using the Stormpath Admin, I can login.

So my original error is fixed, but an issue with verification seems to remain.

**Comment by robertjd** [comment] 2015-06-29 21:22
Hi @iotaweb - glad to hear you've had progress!  If you're still stuck with email verification, can you look at the console in the browser to see if there are any errors?  Feel free to open a new issue here, or contact us on support.  I'm going to close this issue out, thanks!

**Closed as completed by robertjd** 2015-06-29 21:22 UTC
