### ISSUE TITLE
Facebook integration doesn't work when used in conjunction with ASP.NET Core backend

### ISSUE THREAD

**Issue by Confusingboat** [stormpath/stormpath-sdk-angularjs#160] opened 2016-08-02 01:46 UTC
On the Stormpath provided login form in this Angular SDK, the Login with Facebook button disappears when the Angular SPA is placed in front of a Stormpath ASP.NET Core Web API server instead of the Stormpath NodeJS dev server. The ASP.NET Core `/login` endpoint shows its own Facebook button and works just fine, so it appears to be an issue with this SDK.

**Comment by robertjd** [comment] 2016-08-02 01:53
Thanks @Confusingboat , I'll check with @nbarbettini to see if the ASP.NET Core integration is adding the account store provider information to the login view model.  The login view model is served when this Angular SDK makes a JSON GET request to /login, the model contains the information needed to render the login form (including 3rd party provider stores like Facebook).  You'll see this request in your network inspector when you load the login view in Angular.

**Comment by nbarbettini** [comment] 2016-08-02 18:32
Hey @Confusingboat - I think this is a bug on my side. I've created an issue you can track: https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/24

Sorry about the trouble. I'll get this fixed!

**Comment by nbarbettini** [comment] 2016-09-25 23:45
See the comment over at https://github.com/stormpath/stormpath-dotnet-owin-middleware/issues/24 re: fixed and pending release.

I'll close this issue once release 2.1.0 is live.

**Comment by nbarbettini** [comment] 2016-09-25 23:45
Minor note: the ASP.NET Core integration only works correctly if the Angular SDK posts with `application/json` - see https://github.com/stormpath/stormpath-sdk-angularjs/issues/171.

**Comment by nbarbettini** [comment] 2016-10-12 12:39
Hey @Confusingboat - thanks for your patience. My apologies for the long delay. Can you try [Stormpath.AspNetCore v0.7.0](https://www.nuget.org/packages/Stormpath.AspNetCore/0.7.0) or later and see if everything works from Angular now?

**Comment by Confusingboat** [comment] 2016-10-12 13:44
The Facebook button is now displayed and opens the Facebook popup. It still doesn't work for us, though. I'm not sure if this is a problem with our implementation, but I'm getting "Missing login or password." when clicking the Facebook button.

**Comment by nbarbettini** [comment] 2016-10-12 13:47
Darn. Is that message displayed inside the popup, or after you complete the flow via Facebook?

I'll try to repro myself, but if you have a repro project on Github, I can take a look at that too.

**Comment by Confusingboat** [comment] 2016-10-12 13:54
We get that after the Facebook flow, and I have confirmed we're using the built-in stormpath form `sp-login-form`. I'm also seeing a 400 for the post response from `/login`.

**Comment by nbarbettini** [comment] 2016-10-12 13:55
Thanks, looking into it now.

**Comment by nbarbettini** [comment] 2016-10-12 14:04
It's working for me so far - in the 400 response to the POST, is there any error message in the response body?

Also, which version of sdk-angularjs are you using?

**Comment by nbarbettini** [comment] 2016-10-12 14:16
One more thing to check -- this could also be caused by a bad Facebook directory configuration (redirect URI bad, incorrect client secret, etc). Unfortunately the current logging isn't very verbose as to why it failed (just a generic "an error occurred"). I'm working on improving that too.

**Comment by Confusingboat** [comment] 2016-10-12 14:21
It works when I use the vanilla login page at `/login`, so I know it's nothing with the Facebook account or setup.

I opened up Fiddler to have a better look, and it's posting
`providerData[providerId]=facebook&providerData[accessToken]={really long token}`

Response

```
{
  "status": 400,
  "message": "Missing login or password."
}
```

I just noticed that it's posting it as `Content-Type: application/x-www-form-urlencoded`, but I think I remember a comment stating that it only works when posted as `Content-Type: application/json`. Is that correct?

**Comment by nbarbettini** [comment] 2016-10-12 14:25
Ah, yeah. It has to POST as `application/json`. See this issue for configuring the Angular SDK: https://github.com/stormpath/stormpath-sdk-angularjs/issues/171

**Comment by Confusingboat** [comment] 2016-10-12 14:54
After adding the configuration line for `application/json` I can confirm that this now works. Thanks!

**Comment by nbarbettini** [comment] 2016-10-12 14:57
Fantastic. :) The Content-Type should default to the correct value in a future version of the Angular SDK to remove even more friction.

Thanks again for your patience. Ping me or @robertjd again if you run into any other issues.

**Closed as completed by nbarbettini** 2016-10-12 14:57 UTC
